# Generated by Django 5.1.1 on 2024-10-11 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectedLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=1000)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('content', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DirectionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.CharField(max_length=1000)),
                ('distance', models.CharField(max_length=1000)),
                ('duration', models.CharField(max_length=1000)),
                ('detected_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='pages.detectedlocation')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=1000)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('distance', models.FloatField()),
                ('detected_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.detectedlocation')),
                ('request_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.requestlog')),
            ],
        ),
        migrations.AddField(
            model_name='detectedlocation',
            name='request_log',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='detected_locations', to='pages.requestlog'),
        ),
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('request_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_locations', to='pages.requestlog')),
            ],
        ),
    ]
