# Generated by Django 5.1.1 on 2024-10-14 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='user_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image_url',
            field=models.URLField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
