# Generated by Django 5.1.1 on 2024-10-14 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_requestlog_user_id_alter_hotel_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='user_id',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
