# Generated by Django 5.1.1 on 2024-10-14 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_userlocation_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detectedlocation',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='detectedlocation',
            old_name='longitude',
            new_name='lng',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='longitude',
            new_name='lng',
        ),
        migrations.RenameField(
            model_name='userlocation',
            old_name='latitude',
            new_name='lag',
        ),
        migrations.RenameField(
            model_name='userlocation',
            old_name='longitude',
            new_name='lng',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='detected_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='pages.detectedlocation'),
        ),
    ]
