# Generated by Django 5.1.1 on 2024-10-14 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_rename_latitude_detectedlocation_lat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlocation',
            old_name='lag',
            new_name='lat',
        ),
    ]
