# Generated by Django 5.1.1 on 2024-10-07 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_detectedlocation_location_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directionstep',
            name='instruction',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='address',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='pages',
            name='content',
            field=models.CharField(max_length=1000),
        ),
    ]
