# Generated by Django 5.1.1 on 2024-10-07 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_directionstep_instruction_alter_hotel_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='image_url',
            field=models.CharField(default=23, max_length=1500),
            preserve_default=False,
        ),
    ]
