# Generated by Django 5.1.1 on 2024-10-14 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_rename_lag_userlocation_lat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='image_url',
            field=models.CharField(max_length=1000),
        ),
    ]
