# Generated by Django 5.1.1 on 2024-10-14 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_hotel_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestlog',
            old_name='user_id',
            new_name='user_sub',
        ),
    ]
