# Generated by Django 5.1.1 on 2024-10-14 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_rename_user_id_requestlog_user_sub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlocation',
            name='user_id',
        ),
    ]
