# Generated by Django 5.1.1 on 2024-10-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_remove_userlocation_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
