# Generated by Django 5.1.1 on 2024-10-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_requestlog_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
